objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Service_person_assigned__c</fullName>
        <label>Service person assigned</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Not Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>BO-{0000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Mobile_Model_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Mobile Model Details</relationshipLabel>
        <relationshipName>Mobile_Model_Details1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Person</label>
        <referenceTo>Service_Person__c</referenceTo>
        <relationshipLabel>Mobile Model Details</relationshipLabel>
        <relationshipName>Mobile_Model_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Provide__c</fullName>
        <label>Services Provide</label>
        <referenceTo>Services_Provide__c</referenceTo>
        <relationshipLabel>Mobile Model Details</relationshipLabel>
        <relationshipName>Mobile_Model_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Not Assigned</fullName>
                    <default>true</default>
                    <label>Not Assigned</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mobile Model Detail</label>
    <nameField>
        <displayFormat>MO-{0000}</displayFormat>
        <label>Mobile Model No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Model Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Person__c.object
<CustomObject>
    <fields>
        <fullName>Services_Provide__c</fullName>
        <label>Services Provide</label>
        <referenceTo>Services_Provide__c</referenceTo>
        <relationshipLabel>Service Persons</relationshipLabel>
        <relationshipName>Service_Persons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Not active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Person</label>
    <nameField>
        <label>Service Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Services_Provide__c.object
<CustomObject>
    <label>Services Provide</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Provides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/assignPerson.cls
public class assignPerson {
    @InvocableMethod
    public static void getserviceperson(){
        
        Service_Person__c ids;
        Integer count=0;
        List<Service_Person__c> c =[Select Id,Services_Provide__r.Name,Name from Service_Person__c where Status__c='Active'];
        
        //   Booking__c book =[select Id from Booking__c where Service_person_assigned__c='Not Assigned' Limit 1];   
        Mobile_Model_Detail__c mobile =[Select Id,Services_Provide__r.Name from Mobile_Model_Detail__c where Status__c='Not Assigned' limit 1];   
        
        for(Service_Person__c person:c){
            if(mobile.Services_Provide__r.Name==person.Services_Provide__r.Name) {
                
                mobile.Service_Person__c=person.Id;
                mobile.Status__c='Assigned';
                
                person.Status__c='Not active';
                system.debug(mobile);
                system.debug(person);
                break;
            }//break;
        }    
        update mobile;
        update c; 
        
        
        
        
    }
}